"""API route configuration — maps path prefixes to handler modules.

This is the SINGLE source of truth for routing. The router reads this config
to dispatch incoming requests to the correct domain handler.
"""

DOMAIN_HANDLERS = {
    "quiz":             "laso.handlers.patient.quiz_handler",
    "programmes":       "laso.handlers.programme.programme_handler",
    "blood-tests":      "laso.handlers.clinical.blood_test_handler",
    "payments":         "laso.handlers.commerce.payment_handler",
    "consultations":    "laso.handlers.clinical.consultation_handler",
    "prescriptions":    "laso.handlers.clinical.prescription_handler",
    "clinical-notes":   "laso.handlers.clinical.clinical_note_handler",
    "treatment-plans":  "laso.handlers.clinical.treatment_plan_handler",
    "check-ins":        "laso.handlers.patient.check_in_handler",
    "orders":           "laso.handlers.commerce.order_handler",
    "messages":         "laso.handlers.patient.message_handler",
    "tasks":            "laso.handlers.programme.task_handler",
    "refill-requests":  "laso.handlers.commerce.refill_handler",
    "dashboard":        "laso.handlers.patient.dashboard_handler",
    "patients":         "laso.handlers.patient.patient_handler",
    "catalog":          "laso.handlers.admin.admin_catalog_handler",
}

ADMIN_SUB_HANDLERS = {
    "users":      "laso.handlers.admin.admin_handler",
    "doctors":    "laso.handlers.admin.admin_doctor_handler",
    "protocol":   "laso.handlers.admin.admin_protocol_handler",
    "catalog":    "laso.handlers.admin.admin_catalog_handler",
    "analytics":  "laso.handlers.admin.admin_analytics_handler",
}

RESOURCE_PATTERNS = [
    "/quiz/submit",
    "/quiz/result",
    "/quiz/patient/{patientId}",
    "/quiz/claim/{quizId}",
    "/programmes",
    "/programmes/active",
    "/programmes/history",
    "/programmes/{id}",
    "/programmes/{id}/steps",
    "/programmes/{id}/status",
    "/programmes/{id}/steps/{stepId}/status",
    "/blood-tests/{id}",
    "/blood-tests/{id}/results",
    "/blood-tests/programme/{programmeId}",
    "/payments/initiate",
    "/payments/{id}/status",
    "/consultations/today",
    "/consultations/upcoming",
    "/consultations/{id}",
    "/consultations/{id}/context",
    "/consultations/{id}/schedule",
    "/consultations/{id}/meet-link",
    "/consultations/{id}/status",
    "/consultations/patient/{patientId}",
    "/consultations/doctor/{doctorId}",
    "/prescriptions",
    "/prescriptions/{id}/cancel",
    "/prescriptions/patient/{patientId}",
    "/prescriptions/active/{patientId}",
    "/clinical-notes",
    "/clinical-notes/patient/{patientId}",
    "/treatment-plans/programme/{programmeId}",
    "/check-ins",
    "/check-ins/programme/{programmeId}",
    "/check-ins/latest/{patientId}",
    "/check-ins/adherence/{programmeId}",
    "/orders",
    "/orders/recent",
    "/orders/{id}/advance",
    "/orders/patient/{patientId}",
    "/messages",
    "/messages/recent-sent",
    "/messages/{conversationId}",
    "/messages/conversation/{patientId}",
    "/tasks",
    "/tasks/doctor",
    "/tasks/{id}/toggle",
    "/refill-requests",
    "/dashboard/next-action",
    "/patients/me",
    "/patients/me/profile",
    "/patients/{id}",
    "/patients/{id}/flags",
    "/patients/{id}/flags/{flagId}",
    "/patients/doctor/{doctorId}",
    "/patients/doctor/{doctorId}/summary",
    "/catalog/medications",
    "/admin/users",
    "/admin/users/{user_email}",
    "/admin/users/{user_email}/role",
    "/admin/users/{user_email}/status",
    "/admin/users/{user_email}/purge",
    "/admin/doctors",
    "/admin/doctors/{id}",
    "/admin/doctors/{id}/status",
    "/admin/doctors/{id}/availability",
    "/admin/protocol/templates",
    "/admin/protocol/templates/published",
    "/admin/protocol/templates/{id}",
    "/admin/protocol/templates/{id}/versions",
    "/admin/protocol/templates/{id}/steps",
    "/admin/protocol/templates/{id}/steps/reorder",
    "/admin/protocol/templates/{id}/steps/{stepId}",
    "/admin/protocol/templates/{id}/publish",
    "/admin/catalog",
    "/admin/catalog/{id}",
    "/admin/catalog/{id}/stock",
    "/admin/analytics/overview",
    "/admin/analytics/enrolment",
    "/admin/analytics/weight-by-week",
    "/admin/analytics/adherence-trend",
    "/admin/analytics/status-distribution",
    "/admin/analytics/glucose-trend",
    "/admin/analytics/side-effects",
]
